### ISSUE TITLE
Utilize DIY coverage tool for SemanticVersionImpl::SemanticVersionImpl

### ISSUE THREAD

**Issue by ractodev** [DD2480-Group-4/lab3-fabric-loader#6]
Implement flags in this method

**Comment by DouglasFischer** [comment]
Some schanges need to be reverted

row 103-114 in the second image does not need to exist for example

![image](https://github.com/DD2480-Group-4/lab3-fabric-loader/assets/34154299/c8021eb2-5b64-4b85-9de9-e402a3e11b4a)
![image](https://github.com/DD2480-Group-4/lab3-fabric-loader/assets/34154299/cf3e6070-d6fd-451a-9773-cbaa97e1c1a3)

**Comment by DouglasFischer** [comment]
fixed and merged
